name: global_toast
description: global_toast can create toast at everyware, In first Page set Totas.globalContext = context, more info please read readme or example.
version: 2.0.0
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/global_toast

# touch CHANGELOG.md
# touch pubspec.yaml

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  #  entangle:
  #    path: /Users/pillar/work/darts/dart_entangle
  flutter:
    sdk: flutter
